from typing import Union

from fastapi import FastAPI
from youtube_transcript_api import YouTubeTranscriptApi



app = FastAPI()


@app.get("/")
def read_root():
    # iterate over all available transcripts
    # retrieve the available transcripts
    transcript_list = YouTubeTranscriptApi.list_transcripts('hyKyflIG3Us')
    for transcript in transcript_list:

        # the Transcript object provides metadata properties
        # print(
        #     transcript.video_id,
        #     transcript.language,
        #     transcript.language_code,
        #     # whether it has been manually created or generated by YouTube
        #     transcript.is_generated,
        #     # whether this transcript can be translated or not
        #     transcript.is_translatable,
        #     # a list of languages the transcript can be translated to
        #     transcript.translation_languages,
        # )

        # # fetch the actual transcript data
        transcript.fetch()

        # # translating the transcript will return another transcript object
        var = transcript.translate('en').fetch()
        print(transcript.translate('en').fetch())

        # # you can also directly filter for the language you are looking for, using the transcript list
        #transcript = transcript_list.find_transcript(['en'])  

        # # or just filter for manually created transcripts  
        #transcript = transcript_list.find_manually_created_transcript(['hi'])  

        # # or automatically generated ones  
        # transcript = transcript_list.find_generated_transcript(['hi'])
    return {"data": var}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: Union[str, None] = None):
    return {"item_id": item_id, "q": q}